<Project ToolsVersion="Current" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworkVersion>v4.8</TargetFrameworkVersion>
    <PlatformTarget>x64</PlatformTarget>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <StartupObject>YgoMaster.MatchmakingTests</StartupObject>
    <OutputPath>bin\</OutputPath>
    <IntermediateOutputPath>obj\</IntermediateOutputPath>
    <AssemblyName>MatchmakingTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="System" /><Reference Include="System.Core" /><Reference Include="System.Xml" />
    <Reference Include="System.Xml.Linq" /><Reference Include="System.Data" /><Reference Include="System.Data.DataSetExtensions" />
    <Reference Include="Microsoft.CSharp" />
    <Compile Include="..\YgoMasterServer\**\*.cs" Exclude="..\YgoMasterServer\obj\**;..\YgoMasterServer\bin\**" />
    <Compile Include="MatchmakingTests.cs" />
  </ItemGroup>
  <Import Project="$(MSBuildToolsPath)\Microsoft.CSharp.targets" />
</Project>
